version: '3.8'
services:
  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"
      - "16379:16379"
    command: ["redis-server"]
    #command: redis-server --save 60 1 --loglevel warning --requirepass "$REDIS_PASSWORD"
    #environment:
       # - REDIS_PASSWORD=myredispass

networks:
  app-network:
    driver: bridge
